### ISSUE TITLE
Stale branches

### ISSUE THREAD

**Issue by zickgraf** [homalg-project/FinGSetsForCAP#14]
The stale branches `ObjectifyForCAP` and `tmp` are development branches with many temporary commits. All important changes are merged, so the branches can be deleted.

**Comment by mohamed-barakat** [comment]
I agree.

**Comment by zickgraf** [comment]
I do not have the permissions to delete branches in this repository. Can you delete them?

**Comment by mohamed-barakat** [comment]
Done.

**Comment by zickgraf** [comment]
Thanks!
